CREATE TYPE "public"."mainnet_readiness_status" AS ENUM('GO', 'NO_GO');--> statement-breakpoint
CREATE TABLE "mainnet_readiness_audits" (
	"id" text PRIMARY KEY NOT NULL,
	"idempotency_key" text NOT NULL,
	"report_hash" text NOT NULL,
	"status" "mainnet_readiness_status" NOT NULL,
	"all_checks_passed" boolean NOT NULL,
	"sdk_version" text NOT NULL,
	"network" text NOT NULL,
	"lbtc_asset_id" text NOT NULL,
	"usdt_asset_id" text NOT NULL,
	"usdt_precision" integer NOT NULL,
	"usdc_configured" boolean NOT NULL,
	"working_dir_persistent" boolean NOT NULL,
	"operator_named" boolean NOT NULL,
	"max_slippage_bps" integer NOT NULL,
	"external_probe_enabled" boolean NOT NULL,
	"external_execution_attempted" boolean NOT NULL,
	"route_prepared" boolean NOT NULL,
	"receiver_amount_units" bigint,
	"estimated_asset_fees_units" bigint,
	"quote_prepared_at" timestamp with time zone,
	"quote_expires_at" timestamp with time zone,
	"wallet_btc_sats" bigint NOT NULL,
	"refundable_count" integer NOT NULL,
	"unknown_payment_count" integer NOT NULL,
	"reconciliation_matched" boolean NOT NULL,
	"backup_restore_verified" boolean NOT NULL,
	"backup_proof_hash" text,
	"checks" jsonb NOT NULL,
	"completed_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "mainnet_readiness_audits_idempotency_key_unique" UNIQUE("idempotency_key"),
	CONSTRAINT "mainnet_readiness_status_consistent" CHECK (("mainnet_readiness_audits"."status" = 'GO'::mainnet_readiness_status) = "mainnet_readiness_audits"."all_checks_passed"),
	CONSTRAINT "mainnet_readiness_report_hash_shape" CHECK ("mainnet_readiness_audits"."report_hash" ~ '^[a-f0-9]{64}$'),
	CONSTRAINT "mainnet_readiness_mainnet_only" CHECK ("mainnet_readiness_audits"."network" = 'mainnet'),
	CONSTRAINT "mainnet_readiness_asset_allowlist" CHECK ("mainnet_readiness_audits"."lbtc_asset_id" = '6f0279e9ed041c3d710a9f57d0c02928416460c4b722ae3457a11eec381c526d' and "mainnet_readiness_audits"."usdt_asset_id" = 'ce091c998b83c78bb71a632313ba3760f1763d9cfcffae02258ffa9865a37bd2' and "mainnet_readiness_audits"."usdt_precision" = 8 and "mainnet_readiness_audits"."usdc_configured" is false),
	CONSTRAINT "mainnet_readiness_no_execution" CHECK ("mainnet_readiness_audits"."external_execution_attempted" is false),
	CONSTRAINT "mainnet_readiness_ranges" CHECK ("mainnet_readiness_audits"."wallet_btc_sats" >= 0 and "mainnet_readiness_audits"."wallet_btc_sats" <= 10000 and "mainnet_readiness_audits"."refundable_count" >= 0 and "mainnet_readiness_audits"."unknown_payment_count" >= 0 and "mainnet_readiness_audits"."max_slippage_bps" >= 0 and "mainnet_readiness_audits"."max_slippage_bps" <= 100),
	CONSTRAINT "mainnet_readiness_route_values" CHECK (("mainnet_readiness_audits"."route_prepared" is false and "mainnet_readiness_audits"."receiver_amount_units" is null and "mainnet_readiness_audits"."estimated_asset_fees_units" is null and "mainnet_readiness_audits"."quote_prepared_at" is null and "mainnet_readiness_audits"."quote_expires_at" is null) or ("mainnet_readiness_audits"."route_prepared" is true and "mainnet_readiness_audits"."receiver_amount_units" > 0 and "mainnet_readiness_audits"."estimated_asset_fees_units" >= 0 and "mainnet_readiness_audits"."quote_prepared_at" is not null and "mainnet_readiness_audits"."quote_expires_at" > "mainnet_readiness_audits"."quote_prepared_at" and "mainnet_readiness_audits"."quote_expires_at" <= "mainnet_readiness_audits"."quote_prepared_at" + interval '60 seconds' and "mainnet_readiness_audits"."estimated_asset_fees_units" * 10000 <= "mainnet_readiness_audits"."receiver_amount_units" * "mainnet_readiness_audits"."max_slippage_bps")),
	CONSTRAINT "mainnet_readiness_go_requires_operational_proofs" CHECK ("mainnet_readiness_audits"."status" <> 'GO'::mainnet_readiness_status or ("mainnet_readiness_audits"."working_dir_persistent" is true and "mainnet_readiness_audits"."operator_named" is true and "mainnet_readiness_audits"."external_probe_enabled" is true and "mainnet_readiness_audits"."external_execution_attempted" is false and "mainnet_readiness_audits"."route_prepared" is true and "mainnet_readiness_audits"."quote_prepared_at" <= "mainnet_readiness_audits"."completed_at" and "mainnet_readiness_audits"."quote_expires_at" > "mainnet_readiness_audits"."completed_at" and "mainnet_readiness_audits"."reconciliation_matched" is true and "mainnet_readiness_audits"."backup_restore_verified" is true and "mainnet_readiness_audits"."backup_proof_hash" ~ '^[a-f0-9]{64}$' and "mainnet_readiness_audits"."refundable_count" = 0 and "mainnet_readiness_audits"."unknown_payment_count" = 0))
);
